# themes from https://github.com/alacritty/alacritty-theme
import = ["~/dotfiles/alacritty/custom_argonaut.toml"]

# https://alacritty.org/config-alacritty.html
[font]
size = 20

[font.normal]
family = "UbuntuMono Nerd Font Mono"

[window]
startup_mode = "Fullscreen"
decorations = "Full"

[window.padding]
x = 7
y = 20
